### ISSUE TITLE
Unsupported engine?

### ISSUE THREAD

**Issue by ConceptzX** [mckaywrigley/ai-code-translator#42]
I'm getting these errors.

![image](https://github.com/mckaywrigley/ai-code-translator/assets/114145901/5af93bac-f5ff-49bd-b89f-e9040d05e58f)

**Comment by mbs0221** [comment]
I got similar errors.
```
~/ai-code-translator$ npm i
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-import-resolver-typescript@3.5.4',
npm WARN EBADENGINE   required: { node: '^14.18.0 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eventsource-parser@1.0.0',
npm WARN EBADENGINE   required: { node: '>=14.18' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'next@13.2.4',
npm WARN EBADENGINE   required: { node: '>=14.6.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'synckit@0.8.5',
npm WARN EBADENGINE   required: { node: '^14.18.0 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

up to date, audited 346 packages in 32s

116 packages are looking for funding
  run `npm fund` for details

4 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
```
```
~/ai-code-translator$ npm run dev

> code-translate@0.1.0 dev
> next dev

/home/benshan/ai-code-translator/node_modules/next/dist/cli/next-dev.js:362
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.dev (/home/benshan/ai-code-translator/node_modules/next/dist/lib/commands.js:10:30)
    at Object.<anonymous> (/home/benshan/ai-code-translator/node_modules/next/dist/bin/next:141:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
```

**Comment by ccpwer** [comment]
npm audit fix --force
